-- Interview Preparation Crew Tables
-- Stores the overall session and user inputs
CREATE TABLE IF NOT EXISTS interview_prep_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    target_role TEXT NOT NULL,
    target_companies TEXT NOT NULL,
    user_resume TEXT NOT NULL,
    current_stage TEXT DEFAULT 'prospecting', -- 'prospecting', 'researching', 'writing', 'completed'
    final_guide TEXT
);

-- Stores the roles extracted by the Prospector
CREATE TABLE IF NOT EXISTS interview_prep_roles (
    role_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES interview_prep_sessions(session_id) ON DELETE CASCADE,
    company_name TEXT NOT NULL,
    job_title TEXT NOT NULL,
    responsibilities TEXT,
    required_skills TEXT
);

-- Stores the questions generated by the Researcher
CREATE TABLE IF NOT EXISTS interview_prep_questions (
    question_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role_id UUID REFERENCES interview_prep_roles(role_id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_type TEXT -- 'technical' or 'behavioral'
);
